### ISSUE TITLE
What primary editor are you using nowadays Miguel

### ISSUE THREAD

**Issue by Taariqq** [Brackets-Themes/Solarized#3]
Hi Miguel,

Just wondering if you are still using Brackets for your day-to-day job. I find Bracket's Live Preview second to none, but VS Code is pulling away fast.

**Comment by MiguelCastillo** [comment]
Hello - I have been using VS code for a while now.  It does things really well.

**Comment by Taariqq** [comment]
Not to keep bothering you. But, have you found an alternative to the - Live Preview - in Code?
I do some PHP editing and all I am looking for is a) reload browser on save and b) switch files in browser as I switch in the editor.
Appreciate it much.

**Comment by MiguelCastillo** [comment]
Hi @Taariqq no need to apologize.  These are great questions!  So I personally never really used Live Preview besides just giving it a quick try. Im not entirely sure if there is an alternative in VS Code either since I have not really looked for it either. 

So as far as "a" goes, Im not sure if there are alternatives specific to PHP (im not very familiar with the PHP ecosystem), but I suspect you can use something like livereload, which is an editor agnostic tool for refreshing the page whenever there is a change in a file being watched by a file watcher.  Im not entirely sure what you mean by "switch files in browser as I switch in the editor", but that sounds like it would be address by livereload since it does a page refresh which would cause changes in the editor (VS Code) to reflect in the browser.

**Comment by Taariqq** [comment]
Miguel,

Thanks for taking the time. Yes, I have given LiveReload a try and I found it to be lacking. I have to switch to files manually so that is another pain once you have gotten used to Brackets.
What I mean by switching files is that suppose I have two files, index.php and contact.php. As I turn on live preview in bracktes and as I work on index.php, I would see the changes upon save. While withing brackets when I do Ctrl+Tab to switch to contact.php, the "view" in browser also changes to contact.php, such that when I do a save after changes to contact.php I see it instantly. I do not have to go to the browser and manually switch from index.php to contact.php. This is what I find to be the most awesome thing.
